services:
  - type: web
    name: aramco-review-backend
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: MONGO_URI
        value: your_mongodb_connection_string_here
      - key: JWT_SECRET
        value: aramco_review_secret_key_2025
      - key: NODE_ENV
        value: production